[pcm038] check before update if server is alive
With this patch it's checked if the server is alive before erasing the flash

Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>

diff --git a/board/pcm038/env/bin/_update b/board/pcm038/env/bin/_update
--- a/board/pcm038/env/bin/_update
+++ b/board/pcm038/env/bin/_update
@@ -18,10 +18,19 @@ if [ x$ip = xdhcp ]; then
 	dhcp
 fi
 
+ping $eth0.serverip
+if [ $? -ne 0 ] ; then
+	echo "update aborted"
+	exit 1
+fi
+
 unprotect $part
 
+echo
 echo "erasing partition $part"
 erase $part
 
+echo
 echo "flashing $image to $part"
+echo
 tftp $image $part
