[ipe337] fix ageing handling
With this path the script "_alternate" isn't used anymore,
because the return values somehow get lost.

We use alternate directly for now.

Signed-off-by: Marc Kleine-Budde <mkl@pengutronix.de>

diff --git a/board/ipe337/env/bin/update_kernel b/board/ipe337/env/bin/update_kernel
--- a/board/ipe337/env/bin/update_kernel
+++ b/board/ipe337/env/bin/update_kernel
@@ -4,8 +4,13 @@
 
 image=$uimage
 
-. /env/bin/_alternate
-if [ $? = 2 ]; then
+alternate $ageing
+ret=$?
+
+if [ $ret = 0 ]; then
+	echo "Error when accesing ageing-partition!"
+	exit 1
+elif [ $ret = 2 ]; then
 	part=/dev/nor0.kernel0
 else
 	part=/dev/nor0.kernel1
